# Generated by Django 3.0 on 2021-07-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='refersh_token',
            new_name='refresh_token',
        ),
    ]
