# Generated by Django 3.0 on 2021-07-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20210731_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='exprires_in',
            new_name='expires_in',
        ),
    ]
